name: Haskell CI

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2.7.0
        with:
          enable-stack: true
      - name: Stack build
        run: stack build --test --no-run-tests
      - name: Stack test
        run: stack test
